version: '3.8'

services:
  warehouse:
    image: postgres:15-alpine
    container_name: gsc_warehouse
    environment:
      POSTGRES_DB: gsc_db
      POSTGRES_USER: gsc_user
      POSTGRES_PASSWORD: gsc_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gsc_user -d gsc_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - gsc_network

volumes:
  postgres_data:
    driver: local

networks:
  gsc_network:
    driver: bridge
