"""
Jira channel implementation
"""
import requests
from typing import Dict, Any
from datetime import datetime
from .base import Channel, DispatchResult


class JiraChannel(Channel):
    """Jira REST API channel for creating issues from insights"""
    
    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self.base_url = config.get('base_url')
        self.username = config.get('username')
        self.api_token = config.get('api_token')
        self.project_key = config.get('project_key', 'SEO')
        self.issue_type = config.get('issue_type', 'Bug')
    
    def validate_config(self) -> bool:
        """Validate Jira configuration"""
        if not self.enabled:
            return False
        
        if not all([self.base_url, self.username, self.api_token]):
            self.logger.error("Jira credentials not fully configured")
            return False
        
        return True
    
    def format_message(self, insight: Any) -> Dict[str, Any]:
        """
        Format insight as Jira issue
        
        Args:
            insight: Insight object
            
        Returns:
            Jira issue payload
        """
        # Map severity to Jira priority
        priority_map = {
            'critical': 'Highest',
            'high': 'High',
            'medium': 'Medium',
            'low': 'Low'
        }
        
        # Build description
        description = f"{insight.description}\n\n"
        description += f"*Property:* {insight.property}\n"
        description += f"*Category:* {insight.category.value}\n"
        description += f"*Confidence:* {int(insight.confidence * 100)}%\n"
        
        if insight.entity_id:
            description += f"*Entity:* {insight.entity_id}\n"
        
        if insight.metrics:
            description += "\n*Metrics:*\n"
            for key, value in insight.metrics.items():
                label = key.replace('_', ' ').title()
                if isinstance(value, float):
                    if 'change' in key.lower():
                        description += f"- {label}: {value:+.1f}%\n"
                    else:
                        description += f"- {label}: {value:,.2f}\n"
                else:
                    description += f"- {label}: {value}\n"
        
        if insight.actions:
            description += "\n*Recommended Actions:*\n"
            for action in insight.actions:
                description += f"- {action}\n"
        
        description += f"\n_Generated by GSC Insight Engine ({insight.source}) at {insight.generated_at.isoformat()}_"
        
        # Build issue payload
        payload = {
            "fields": {
                "project": {
                    "key": self.project_key
                },
                "summary": insight.title,
                "description": description,
                "issuetype": {
                    "name": self.issue_type
                },
                "priority": {
                    "name": priority_map.get(insight.severity, 'Medium')
                },
                "labels": [
                    "gsc-insight",
                    f"severity-{insight.severity}",
                    f"category-{insight.category.value}"
                ]
            }
        }
        
        return payload
    
    def send(self, insight: Any, **kwargs) -> DispatchResult:
        """
        Create Jira issue for insight
        
        Args:
            insight: Insight to send
            **kwargs: Additional parameters
            
        Returns:
            DispatchResult
        """
        start_time = datetime.utcnow()
        
        # Dry run mode
        if self.dry_run:
            self.logger.info(f"[DRY RUN] Would create Jira issue: {insight.title}")
            return DispatchResult(
                success=True,
                channel='jira',
                insight_id=insight.id,
                timestamp=start_time,
                response={'dry_run': True}
            )
        
        # Validate config
        if not self.validate_config():
            return DispatchResult(
                success=False,
                channel='jira',
                insight_id=insight.id,
                timestamp=start_time,
                error="Jira not configured correctly"
            )
        
        try:
            # Format issue
            payload = self.format_message(insight)
            
            # Create issue via REST API
            url = f"{self.base_url}/rest/api/3/issue"
            
            response = requests.post(
                url,
                json=payload,
                auth=(self.username, self.api_token),
                headers={'Content-Type': 'application/json'},
                timeout=10
            )
            
            response.raise_for_status()
            
            issue_data = response.json()
            issue_key = issue_data.get('key')
            
            self.logger.info(f"Created Jira issue {issue_key} for insight: {insight.title}")
            
            return DispatchResult(
                success=True,
                channel='jira',
                insight_id=insight.id,
                timestamp=datetime.utcnow(),
                response={
                    'issue_key': issue_key,
                    'issue_url': f"{self.base_url}/browse/{issue_key}"
                }
            )
            
        except requests.exceptions.RequestException as e:
            self.logger.error(f"Failed to create Jira issue: {e}")
            return DispatchResult(
                success=False,
                channel='jira',
                insight_id=insight.id,
                timestamp=datetime.utcnow(),
                error=str(e)
            )
        except Exception as e:
            self.logger.error(f"Unexpected error creating Jira issue: {e}", exc_info=True)
            return DispatchResult(
                success=False,
                channel='jira',
                insight_id=insight.id,
                timestamp=datetime.utcnow(),
                error=str(e)
            )
